export default function handler(req: any, res: any) {
  res.status(200).json([
    {
      name: "The Cãptain",
      profileIconId: 5168,
      summonerLevel: 272,
      rank: "IV",
      lp: 0,
      tier: "PLATINUM",
      wins: 204,
      losses: 184,
      champStats: [
        {
          champion: "Jinx",
          stats: {
            matches: 200,
            wins: 112,
            kills: 1510,
            deaths: 1175,
            assists: 1531,
            cs: 42564,
          },
        },
        {
          champion: "Jhin",
          stats: {
            matches: 61,
            wins: 31,
            kills: 432,
            deaths: 311,
            assists: 474,
            cs: 12216,
          },
        },
        {
          champion: "Caitlyn",
          stats: {
            matches: 31,
            wins: 14,
            kills: 188,
            deaths: 158,
            assists: 201,
            cs: 5797,
          },
        },
        {
          champion: "LeeSin",
          stats: {
            matches: 2,
            wins: 1,
            kills: 4,
            deaths: 11,
            assists: 13,
            cs: 73,
          },
        },
        {
          champion: "Kaisa",
          stats: {
            matches: 20,
            wins: 12,
            kills: 194,
            deaths: 120,
            assists: 124,
            cs: 4327,
          },
        },
        {
          champion: "Lucian",
          stats: {
            matches: 16,
            wins: 10,
            kills: 151,
            deaths: 87,
            assists: 106,
            cs: 3443,
          },
        },
        {
          champion: "Xayah",
          stats: {
            matches: 36,
            wins: 16,
            kills: 253,
            deaths: 178,
            assists: 239,
            cs: 7895,
          },
        },
        {
          champion: "Lulu",
          stats: {
            matches: 1,
            wins: 1,
            kills: 2,
            deaths: 4,
            assists: 15,
            cs: 29,
          },
        },
        {
          champion: "Shen",
          stats: {
            matches: 1,
            wins: 0,
            kills: 2,
            deaths: 3,
            assists: 0,
            cs: 78,
          },
        },
        {
          champion: "Aphelios",
          stats: {
            matches: 7,
            wins: 2,
            kills: 50,
            deaths: 48,
            assists: 28,
            cs: 1420,
          },
        },
        {
          champion: "Zac",
          stats: {
            matches: 1,
            wins: 0,
            kills: 0,
            deaths: 5,
            assists: 2,
            cs: 10,
          },
        },
        {
          champion: "Tristana",
          stats: {
            matches: 8,
            wins: 2,
            kills: 56,
            deaths: 42,
            assists: 36,
            cs: 1524,
          },
        },
        {
          champion: "Ezreal",
          stats: {
            matches: 1,
            wins: 0,
            kills: 7,
            deaths: 6,
            assists: 7,
            cs: 262,
          },
        },
        {
          champion: "Zeri",
          stats: {
            matches: 1,
            wins: 1,
            kills: 6,
            deaths: 2,
            assists: 14,
            cs: 166,
          },
        },
        {
          champion: "Twitch",
          stats: {
            matches: 1,
            wins: 1,
            kills: 8,
            deaths: 5,
            assists: 13,
            cs: 162,
          },
        },
        {
          champion: "Veigar",
          stats: {
            matches: 1,
            wins: 1,
            kills: 6,
            deaths: 7,
            assists: 17,
            cs: 237,
          },
        },
      ],
    },
    {
      name: "Gdiino",
      profileIconId: 4499,
      summonerLevel: 217,
      rank: "IV",
      lp: 75,
      tier: "GOLD",
      wins: 227,
      losses: 213,
      champStats: [
        {
          champion: "Shaco",
          stats: {
            matches: 39,
            wins: 23,
            kills: 331,
            deaths: 217,
            assists: 304,
            cs: 1479,
          },
        },
        {
          champion: "Vi",
          stats: {
            matches: 2,
            wins: 0,
            kills: 4,
            deaths: 12,
            assists: 7,
            cs: 94,
          },
        },
        {
          champion: "Diana",
          stats: {
            matches: 104,
            wins: 53,
            kills: 660,
            deaths: 660,
            assists: 779,
            cs: 4780,
          },
        },
        {
          champion: "Pyke",
          stats: {
            matches: 1,
            wins: 1,
            kills: 2,
            deaths: 9,
            assists: 10,
            cs: 37,
          },
        },
        {
          champion: "Lillia",
          stats: {
            matches: 2,
            wins: 2,
            kills: 20,
            deaths: 4,
            assists: 13,
            cs: 67,
          },
        },
        {
          champion: "XinZhao",
          stats: {
            matches: 18,
            wins: 7,
            kills: 95,
            deaths: 102,
            assists: 128,
            cs: 676,
          },
        },
        {
          champion: "Hecarim",
          stats: {
            matches: 9,
            wins: 4,
            kills: 54,
            deaths: 56,
            assists: 80,
            cs: 340,
          },
        },
        {
          champion: "Nunu",
          stats: {
            matches: 4,
            wins: 3,
            kills: 22,
            deaths: 31,
            assists: 64,
            cs: 196,
          },
        },
        {
          champion: "Khazix",
          stats: {
            matches: 6,
            wins: 2,
            kills: 23,
            deaths: 32,
            assists: 30,
            cs: 122,
          },
        },
        {
          champion: "Graves",
          stats: {
            matches: 1,
            wins: 0,
            kills: 8,
            deaths: 12,
            assists: 6,
            cs: 62,
          },
        },
        {
          champion: "Yasuo",
          stats: {
            matches: 1,
            wins: 0,
            kills: 1,
            deaths: 7,
            assists: 3,
            cs: 140,
          },
        },
        {
          champion: "Trundle",
          stats: {
            matches: 115,
            wins: 69,
            kills: 705,
            deaths: 669,
            assists: 981,
            cs: 6326,
          },
        },
        {
          champion: "JarvanIV",
          stats: {
            matches: 13,
            wins: 5,
            kills: 61,
            deaths: 88,
            assists: 172,
            cs: 538,
          },
        },
        {
          champion: "LeeSin",
          stats: {
            matches: 76,
            wins: 31,
            kills: 432,
            deaths: 507,
            assists: 694,
            cs: 2556,
          },
        },
        {
          champion: "Warwick",
          stats: {
            matches: 4,
            wins: 2,
            kills: 29,
            deaths: 27,
            assists: 38,
            cs: 181,
          },
        },
        {
          champion: "Rammus",
          stats: {
            matches: 30,
            wins: 17,
            kills: 133,
            deaths: 176,
            assists: 383,
            cs: 807,
          },
        },
        {
          champion: "Amumu",
          stats: {
            matches: 1,
            wins: 0,
            kills: 2,
            deaths: 8,
            assists: 7,
            cs: 23,
          },
        },
        {
          champion: "Viego",
          stats: {
            matches: 1,
            wins: 0,
            kills: 2,
            deaths: 13,
            assists: 10,
            cs: 40,
          },
        },
        {
          champion: "Karthus",
          stats: {
            matches: 1,
            wins: 1,
            kills: 2,
            deaths: 8,
            assists: 8,
            cs: 66,
          },
        },
        {
          champion: "Kayn",
          stats: {
            matches: 1,
            wins: 0,
            kills: 8,
            deaths: 8,
            assists: 5,
            cs: 44,
          },
        },
        {
          champion: "Shyvana",
          stats: {
            matches: 11,
            wins: 7,
            kills: 99,
            deaths: 59,
            assists: 91,
            cs: 842,
          },
        },
      ],
    },
    {
      name: "Zorro",
      profileIconId: 4655,
      summonerLevel: 268,
      rank: "IV",
      lp: 75,
      tier: "DIAMOND",
      wins: 64,
      losses: 37,
      champStats: [
        {
          champion: "Rakan",
          stats: {
            matches: 54,
            wins: 35,
            kills: 70,
            deaths: 214,
            assists: 835,
            cs: 1756,
          },
        },
        {
          champion: "Thresh",
          stats: {
            matches: 5,
            wins: 3,
            kills: 3,
            deaths: 22,
            assists: 72,
            cs: 168,
          },
        },
        {
          champion: "Nautilus",
          stats: {
            matches: 4,
            wins: 2,
            kills: 7,
            deaths: 30,
            assists: 53,
            cs: 122,
          },
        },
        {
          champion: "Karma",
          stats: {
            matches: 1,
            wins: 0,
            kills: 2,
            deaths: 5,
            assists: 4,
            cs: 5,
          },
        },
        {
          champion: "Renata",
          stats: {
            matches: 17,
            wins: 12,
            kills: 25,
            deaths: 68,
            assists: 308,
            cs: 239,
          },
        },
        {
          champion: "Blitzcrank",
          stats: {
            matches: 12,
            wins: 7,
            kills: 20,
            deaths: 67,
            assists: 152,
            cs: 372,
          },
        },
        {
          champion: "Galio",
          stats: {
            matches: 1,
            wins: 0,
            kills: 2,
            deaths: 5,
            assists: 5,
            cs: 249,
          },
        },
        {
          champion: "Alistar",
          stats: {
            matches: 5,
            wins: 3,
            kills: 5,
            deaths: 21,
            assists: 65,
            cs: 147,
          },
        },
        {
          champion: "Orianna",
          stats: {
            matches: 2,
            wins: 2,
            kills: 4,
            deaths: 8,
            assists: 15,
            cs: 373,
          },
        },
      ],
    },
    {
      name: "Bert Skurt",
      profileIconId: 3466,
      summonerLevel: 302,
      rank: "III",
      lp: 5,
      tier: "SILVER",
      wins: 32,
      losses: 40,
      champStats: [
        {
          champion: "Lulu",
          stats: {
            matches: 5,
            wins: 2,
            kills: 3,
            deaths: 21,
            assists: 63,
            cs: 54,
          },
        },
        {
          champion: "Xerath",
          stats: {
            matches: 6,
            wins: 3,
            kills: 25,
            deaths: 23,
            assists: 63,
            cs: 268,
          },
        },
        {
          champion: "Caitlyn",
          stats: {
            matches: 2,
            wins: 1,
            kills: 10,
            deaths: 4,
            assists: 6,
            cs: 301,
          },
        },
        {
          champion: "Thresh",
          stats: {
            matches: 2,
            wins: 1,
            kills: 4,
            deaths: 13,
            assists: 15,
            cs: 57,
          },
        },
        {
          champion: "Corki",
          stats: {
            matches: 2,
            wins: 0,
            kills: 16,
            deaths: 16,
            assists: 17,
            cs: 344,
          },
        },
        {
          champion: "Brand",
          stats: {
            matches: 1,
            wins: 0,
            kills: 3,
            deaths: 6,
            assists: 6,
            cs: 53,
          },
        },
        {
          champion: "Janna",
          stats: {
            matches: 12,
            wins: 6,
            kills: 8,
            deaths: 32,
            assists: 139,
            cs: 166,
          },
        },
        {
          champion: "Sona",
          stats: {
            matches: 2,
            wins: 2,
            kills: 4,
            deaths: 7,
            assists: 48,
            cs: 23,
          },
        },
        {
          champion: "Swain",
          stats: {
            matches: 3,
            wins: 1,
            kills: 13,
            deaths: 21,
            assists: 35,
            cs: 55,
          },
        },
        {
          champion: "Senna",
          stats: {
            matches: 3,
            wins: 2,
            kills: 18,
            deaths: 24,
            assists: 58,
            cs: 111,
          },
        },
        {
          champion: "Kaisa",
          stats: {
            matches: 2,
            wins: 1,
            kills: 8,
            deaths: 13,
            assists: 16,
            cs: 361,
          },
        },
        {
          champion: "Seraphine",
          stats: {
            matches: 1,
            wins: 1,
            kills: 4,
            deaths: 2,
            assists: 17,
            cs: 23,
          },
        },
        {
          champion: "Veigar",
          stats: {
            matches: 1,
            wins: 0,
            kills: 3,
            deaths: 3,
            assists: 4,
            cs: 169,
          },
        },
        {
          champion: "Karma",
          stats: {
            matches: 3,
            wins: 2,
            kills: 4,
            deaths: 16,
            assists: 52,
            cs: 73,
          },
        },
        {
          champion: "Ahri",
          stats: {
            matches: 1,
            wins: 1,
            kills: 5,
            deaths: 7,
            assists: 7,
            cs: 138,
          },
        },
        {
          champion: "Jinx",
          stats: {
            matches: 2,
            wins: 0,
            kills: 5,
            deaths: 11,
            assists: 7,
            cs: 294,
          },
        },
        {
          champion: "Zeri",
          stats: {
            matches: 3,
            wins: 1,
            kills: 17,
            deaths: 17,
            assists: 28,
            cs: 415,
          },
        },
        {
          champion: "Trundle",
          stats: {
            matches: 1,
            wins: 0,
            kills: 7,
            deaths: 11,
            assists: 16,
            cs: 31,
          },
        },
        {
          champion: "Chogath",
          stats: {
            matches: 1,
            wins: 1,
            kills: 1,
            deaths: 1,
            assists: 0,
            cs: 134,
          },
        },
        {
          champion: "Teemo",
          stats: {
            matches: 1,
            wins: 0,
            kills: 4,
            deaths: 8,
            assists: 0,
            cs: 212,
          },
        },
        {
          champion: "Renekton",
          stats: {
            matches: 1,
            wins: 1,
            kills: 2,
            deaths: 5,
            assists: 5,
            cs: 206,
          },
        },
        {
          champion: "Malphite",
          stats: {
            matches: 1,
            wins: 1,
            kills: 7,
            deaths: 3,
            assists: 14,
            cs: 116,
          },
        },
        {
          champion: "Akshan",
          stats: {
            matches: 2,
            wins: 0,
            kills: 4,
            deaths: 9,
            assists: 5,
            cs: 288,
          },
        },
        {
          champion: "Tryndamere",
          stats: {
            matches: 1,
            wins: 0,
            kills: 2,
            deaths: 6,
            assists: 3,
            cs: 193,
          },
        },
        {
          champion: "Graves",
          stats: {
            matches: 1,
            wins: 1,
            kills: 4,
            deaths: 10,
            assists: 8,
            cs: 217,
          },
        },
        {
          champion: "Shen",
          stats: {
            matches: 12,
            wins: 4,
            kills: 52,
            deaths: 67,
            assists: 132,
            cs: 1854,
          },
        },
      ],
    },
    {
      name: "Queen Raka",
      profileIconId: 1299,
      summonerLevel: 322,
      rank: "I",
      lp: 69,
      tier: "GOLD",
      wins: 38,
      losses: 32,
      champStats: [
        {
          champion: "Morgana",
          stats: {
            matches: 1,
            wins: 0,
            kills: 1,
            deaths: 12,
            assists: 14,
            cs: 17,
          },
        },
        {
          champion: "Soraka",
          stats: {
            matches: 10,
            wins: 5,
            kills: 10,
            deaths: 48,
            assists: 141,
            cs: 233,
          },
        },
        {
          champion: "Lulu",
          stats: {
            matches: 3,
            wins: 2,
            kills: 6,
            deaths: 14,
            assists: 49,
            cs: 55,
          },
        },
        {
          champion: "Nami",
          stats: {
            matches: 1,
            wins: 1,
            kills: 1,
            deaths: 6,
            assists: 20,
            cs: 16,
          },
        },
        {
          champion: "Lux",
          stats: {
            matches: 2,
            wins: 1,
            kills: 8,
            deaths: 20,
            assists: 34,
            cs: 97,
          },
        },
        {
          champion: "Janna",
          stats: {
            matches: 16,
            wins: 9,
            kills: 11,
            deaths: 60,
            assists: 235,
            cs: 359,
          },
        },
        {
          champion: "Renata",
          stats: {
            matches: 8,
            wins: 6,
            kills: 15,
            deaths: 47,
            assists: 158,
            cs: 152,
          },
        },
        {
          champion: "Karma",
          stats: {
            matches: 1,
            wins: 0,
            kills: 2,
            deaths: 8,
            assists: 24,
            cs: 20,
          },
        },
        {
          champion: "Nautilus",
          stats: {
            matches: 1,
            wins: 0,
            kills: 0,
            deaths: 7,
            assists: 22,
            cs: 32,
          },
        },
        {
          champion: "Veigar",
          stats: {
            matches: 25,
            wins: 14,
            kills: 195,
            deaths: 136,
            assists: 166,
            cs: 4290,
          },
        },
        {
          champion: "Annie",
          stats: {
            matches: 1,
            wins: 0,
            kills: 2,
            deaths: 7,
            assists: 4,
            cs: 147,
          },
        },
        {
          champion: "Shen",
          stats: {
            matches: 1,
            wins: 0,
            kills: 0,
            deaths: 7,
            assists: 3,
            cs: 128,
          },
        },
      ],
    },
  ]);
}
